pipelines:
  - name: Contract Invocations to DuckLake
    source:
      type: BufferedStorageSourceAdapter
      config:
        s3:
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          region: us-east-1
          bucket: stellar-ledgers
          prefix: ledgers/mainnet/
        buffer:
          size: 100
          delay_seconds: 10
        ledger_range:
          start: 59070000
          end: 0
    processors:
      - type: ContractInvocation
        config:
          # Contract invocation processor config
    consumers:
      - type: SaveToDuckLake
        config:
          catalog_path: "ducklake:stellar_contract_invocations.ducklake"
          data_path: "./contract_invocations_data"
          table_name: "contract_invocations"
          schema_name: "main"
          batch_size: 1000
          commit_interval_seconds: 30