pipelines:
  FullLedgerToDuckLake:
    source:
      type: BufferedStorageSourceAdapter
      config:
        bucket_name: "obsrvr-stellar-ledger-data-pubnet-data/landing/ledgers/pubnet"
        network: "mainnet"
        num_workers: 20
        retry_limit: 3
        retry_wait: 5
        start_ledger: 59076383    # Same ledger as AWS example
        end_ledger: 59076390      # Process 8 ledgers
        ledgers_per_file: 1
        files_per_partition: 64000
    
    processors:
      - type: "LedgerToJSON"
        name: "ledger-to-json"
        config:
          network_passphrase: "Public Global Stellar Network ; September 2015"
    
    consumers:
      - type: SaveToDuckLake
        config:
          # DuckLake configuration
          catalog_path: "ducklake:stellar_pipeline.ducklake"
          data_path: "./ducklake_data"  # Local storage, can be S3/GCS
          
          # Table configuration
          table_name: "ledgers_nested"
          schema_name: "main"
          
          # Performance settings
          batch_size: 10                    # Commit every 10 ledgers
          commit_interval_seconds: 30       # Or every 30 seconds
          
          # Connection settings
          max_connections: 5
          
          # Logging
          debug: true

  # Example: Direct transaction analytics to DuckLake
  TransactionAnalyticsToDuckLake:
    source:
      type: BufferedStorageSourceAdapter
      config:
        bucket_name: "obsrvr-stellar-ledger-data-pubnet-data/landing/ledgers/pubnet"
        network: "mainnet"
        num_workers: 10
        start_ledger: 59076383
        end_ledger: 59076390
    
    processors:
      - type: "LedgerReader"
        name: "ledger-reader"
        config:
          network_passphrase: "Public Global Stellar Network ; September 2015"
      
      - type: "AccountTransaction"
        name: "extract-transactions"
        config:
          flatten: true
    
    consumers:
      - type: SaveToDuckLake
        config:
          catalog_path: "ducklake:stellar_pipeline.ducklake"
          data_path: "./ducklake_data"
          table_name: "transaction_analytics"
          schema_name: "main"
          batch_size: 100
          commit_interval_seconds: 10

  # Example: Contract events to DuckLake
  ContractEventsToDuckLake:
    source:
      type: BufferedStorageSourceAdapter
      config:
        bucket_name: "obsrvr-stellar-ledger-data-pubnet-data/landing/ledgers/pubnet"
        network: "mainnet"
        num_workers: 10
        start_ledger: 59076383
        end_ledger: 59076390
    
    processors:
      - type: "ContractEvent"
        name: "contract-event-processor"
        config:
          network_passphrase: "Public Global Stellar Network ; September 2015"
          include_diagnostic_events: false
    
    consumers:
      - type: SaveToDuckLake
        config:
          catalog_path: "ducklake:stellar_pipeline.ducklake"
          data_path: "./ducklake_data"
          table_name: "contract_events"
          schema_name: "main"
          batch_size: 50
          commit_interval_seconds: 15