# Simplified v2 configuration
# Now with automatic network passphrase injection!

source:
  bucket: "obsrvr-stellar-ledger-data-testnet-data/landing/ledgers/testnet"
  network: testnet
  workers: 10
  start_ledger: 503100

# Network passphrase is now automatically injected from source.network
process:
  - latest_ledger

save_to:
  zmq:
    address: "tcp://127.0.0.1:5555"
