# Alternative v2 approach - explicitly specify network passphrase
# This works around the current limitation

source:
  bucket: "obsrvr-stellar-ledger-data-testnet-data/landing/ledgers/testnet"
  network: testnet
  workers: 10
  start_ledger: 503100

process:
  - type: LatestLedger
    config:
      network_passphrase: "Test SDF Network ; September 2015"

save_to:
  zmq:
    address: "tcp://127.0.0.1:5555"