pipelines:
  LatestLedgerPipeline:
    source:
      type: BufferedStorageSourceAdapter
      config:
        bucket_name: "your-bucket-name"
        network: "mainnet"  # or "testnet"
        num_workers: 10
        retry_limit: 3
        retry_wait: 5
        start_ledger: 56077539  # Adjust as needed
        ledgers_per_file: 1
        files_per_partition: 64000
    processors:
      - type: LatestLedger
        config:
          network_passphrase: "Public Global Stellar Network ; September 2015"  # Use "Test SDF Network ; September 2015" for testnet
    consumers:
      - type: SaveLatestLedgerToRedis
        config:
          # Option 1: Local Redis (no TLS)
          redis_address: "localhost:6379"
          redis_password: ""  # No password for local Redis
          redis_db: 0
          key_prefix: "stellar:ledger:"
          use_tls: false  # No TLS for local Redis
          
          # Option 2: Managed Redis with TLS (uncomment and adjust)
          # redis_address: "your-redis-host.example.com:6380"
          # redis_password: "your-redis-password"
          # redis_db: 0
          # key_prefix: "stellar:ledger:"
          # use_tls: true  # Enable TLS for secure connections
          
          # Option 3: Redis URL (uncomment and adjust)
          # redis_url: "redis://localhost:6379/0"  # For local Redis
          # redis_url: "rediss://user:password@your-redis-host.example.com:6380/0"  # For secure Redis
          # key_prefix: "stellar:ledger:" 