pipelines:
  PaymentPipeline:
    source:
      type: BufferedStorageSourceAdapter
      config:
        bucket_name: "bucket-name"
        network: "testnet"
        buffer_size: 640
        num_workers: 10
        retry_limit: 3
        retry_wait: 5
        start_ledger: 539328
    processors:
      - type: TransformToAppPayment
        config:
          network_passphrase: "Test SDF Network ; September 2015"
        - type: TransformToAppTrustline
          config:
            network_passphrase: "Test SDF Network ; September 2015"
      - type: TransformToAppMetrics
        config:
          network_passphrase: "Test SDF Network ; September 2015"
      - type: FilterPayments
        config:
          min_amount: "100.00"
          asset_code: "native"
          network_passphrase: "Test SDF Network ; September 2015"
    consumers:
      - type: SaveToPostgreSQL
        config:
          host: "localhost"
          port: 5432
          database: "stellar_events"
          username: "your_user"
          password: "your_password"
          ssl_mode: "disable"
          max_open_conns: 25
          max_idle_conns: 5
      - type: SaveToExcel
        config:
          file_path: "./data/payments.xlsx"
      - type: SaveToZeroMQ
        config:
          address: "tcp://127.0.0.1:5555"
      - type: SaveToGCS
        config:
          bucket_name: "bucket-name"
          object_name: "demo/filtered_payments_1.xlsx"
          project_id: "project-id"
      - type: SaveToDuckDB
        config:
          db_path: "stellar_operations.duckdb"
      - type: SaveToClickHouse
        config:
          address: "localhost:9000"
          database: "stellar"
          username: "default"
          password: ""
          max_open_conns: 10
          max_idle_conns: 5
      - type: SaveToRedis
        config:
          address: "localhost:6379"
          password: "your-redis-password"
          db: 0
          key_prefix: "stellar:"
          ttl_hours: 24
      - type: NotificationDispatcher
        config:
          slack_token: "xoxb-your-slack-token"
          sendgrid_key: "your-sendgrid-key"
          email_from: "notifications@obsrvr.com"
          email_to: 
            - "team@obsrvr.com"
            - "alerts@obsrvr.com"
          slack_channels:
            - "#stellar-alerts"
            - "#trading-alerts"
          webhook_urls:
            - "https://api.example.com/webhooks/stellar"
          rules:
            - type: "payment"
              condition: "gt"
              field: "amount"
              value: "10000.0"
              channels: ["slack", "email"]
            - type: "create_account"
              condition: "gt"
              field: "starting_balance"
              value: "5000.0"
              channels: ["slack"]
            - type: "trade"
              condition: "gt"
              field: "price"
              value: "1.5"
              channels: ["webhook"]
  FilteredPaymentPipeline:
    source:
      type: BufferedStorageSourceAdapter
      config:
        bucket_name: "bucket-name"
        network: "testnet"
        buffer_size: 640
        num_workers: 10
        retry_limit: 3
        retry_wait: 5
        start_ledger: 539328
    processors:
      - type: FilterPayments
        config:
          asset_code: "native"
          min_amount: "100.00"
          network_passphrase: "Test SDF Network ; September 2015"
    consumers:
      - type: SaveToGCS
        config:
          bucket_name: "bucket-name"
          object_name: "demo/filtered_payments_2.xlsx"
          project_id: "project-id"
 