pipeline:
  name: PaymentPipeline
  source:
    type: CaptiveCoreInboundAdapter
    config:
      network: testnet
      history_archive_urls:
        - https://history.stellar.org/prd/core-live/core_live_001
      core_binary_path: /usr/local/bin/stellar-core
  processors:
    - type: FilterPayments
      config:
        min_amount: "100.00"
        asset_code: "XLM"
    - type: TransformToAppPayment
      config:
        network_passphrase: "Test SDF Network ; September 2015"
  consumers:
    - type: SaveToExcel
      config:
        file_path: /data/payments.xlsx
