pipelines:
  PaymentPipeline:
    source:
      type: BufferedStorageSourceAdapter
      config:
        bucket_name: "bucket-name"
        network: "testnet"
        buffer_size: 640
        num_workers: 10
        retry_limit: 3
        retry_wait: 5
        start_ledger: 539328
    processors:
      - type: CreateAccountTransformer
        config:
          network_passphrase: "Test SDF Network ; September 2015"
    consumers:
      - type: SaveToMongoDB
        config:
          uri: "mongodb_uri"
          database: "mongodb_database"
          collection: "mongodb_collection"
          connect_timeout: 10  # seconds
 