pipelines:
  BlankPipeline:
    source:
      type: BufferedStorageSourceAdapter
      config:
        bucket_name: "mosley-mcs-1/galexie"
        network: "testnet"
        buffer_size: 10
        num_workers: 10
        retry_limit: 3
        retry_wait: 5
        start_ledger: 100
    processors:
      - type: LedgerReader
        config:
          network_passphrase: "Test SDF Network ; September 2015"
      - type: FilterPayments
        config:
          network_passphrase: "Test SDF Network ; September 2015"
          min_amount: "10"
          asset_code: "native"
    consumers:
      - type: SaveAssetToPostgreSQL
        config:
          connection_string: "host=localhost port=5432 user=postgres password=postgres dbname=galexie sslmode=disable"




 