pipelines:
  contract_data_mixed_test:
    name: "Contract Data Mixed Mode Test"
    source:
      type: "BufferedStorageSourceAdapter"
      config:
        bucket_name: "obsrvr-stellar-ledger-data-testnet-data/landing/ledgers/testnet"
        network: "testnet"
        # Mixed mode: start from older ledger, end 10 days ago  
        start_ledger: 300000
        end_time_ago: "10d"
        num_workers: 5
        retry_limit: 3
        retry_wait: 5
        ledgers_per_file: 1
        files_per_partition: 64000
    processors:
      - type: "contract_data"
        config:
          network_passphrase: "Test SDF Network ; September 2015"
          page_size: 50
    consumers:
      - type: "StdoutConsumer"
        config: {}